// Generated by scripts/build_gallery.py; original photos are unchanged.
window.GUXUE_PHOTOS = [
  {
    "id": "mood-1",
    "category": "mood",
    "label": "心情",
    "title": "心情 · 01",
    "src": "images/mood/1.jpg",
    "thumb": "images/thumbs/mood/1.webp",
    "width": 1440,
    "height": 810
  },
  {
    "id": "mood-2",
    "category": "mood",
    "label": "心情",
    "title": "心情 · 02",
    "src": "images/mood/2.jpg",
    "thumb": "images/thumbs/mood/2.webp",
    "width": 1702,
    "height": 1276
  },
  {
    "id": "mood-3",
    "category": "mood",
    "label": "心情",
    "title": "心情 · 03",
    "src": "images/mood/3.jpg",
    "thumb": "images/thumbs/mood/3.webp",
    "width": 1706,
    "height": 1280
  },
  {
    "id": "mood-4",
    "category": "mood",
    "label": "心情",
    "title": "心情 · 04",
    "src": "images/mood/4.jpg",
    "thumb": "images/thumbs/mood/4.webp",
    "width": 1280,
    "height": 1908
  },
  {
    "id": "mood-5",
    "category": "mood",
    "label": "心情",
    "title": "心情 · 05",
    "src": "images/mood/5.jpg",
    "thumb": "images/thumbs/mood/5.webp",
    "width": 1702,
    "height": 1276
  },
  {
    "id": "mood-6",
    "category": "mood",
    "label": "心情",
    "title": "心情 · 06",
    "src": "images/mood/6.jpg",
    "thumb": "images/thumbs/mood/6.webp",
    "width": 1280,
    "height": 1707
  },
  {
    "id": "mood-7",
    "category": "mood",
    "label": "心情",
    "title": "心情 · 07",
    "src": "images/mood/7.jpg",
    "thumb": "images/thumbs/mood/7.webp",
    "width": 2275,
    "height": 1279
  },
  {
    "id": "mood-8",
    "category": "mood",
    "label": "心情",
    "title": "心情 · 08",
    "src": "images/mood/8.jpg",
    "thumb": "images/thumbs/mood/8.webp",
    "width": 1706,
    "height": 960
  },
  {
    "id": "mood-9",
    "category": "mood",
    "label": "心情",
    "title": "心情 · 09",
    "src": "images/mood/9.jpg",
    "thumb": "images/thumbs/mood/9.webp",
    "width": 1278,
    "height": 1922
  },
  {
    "id": "mood-10",
    "category": "mood",
    "label": "心情",
    "title": "心情 · 10",
    "src": "images/mood/10.jpg",
    "thumb": "images/thumbs/mood/10.webp",
    "width": 1279,
    "height": 2028
  },
  {
    "id": "mood-11",
    "category": "mood",
    "label": "心情",
    "title": "心情 · 11",
    "src": "images/mood/11.jpg",
    "thumb": "images/thumbs/mood/11.webp",
    "width": 1920,
    "height": 1080
  },
  {
    "id": "mood-12",
    "category": "mood",
    "label": "心情",
    "title": "心情 · 12",
    "src": "images/mood/12.jpg",
    "thumb": "images/thumbs/mood/12.webp",
    "width": 1920,
    "height": 1080
  },
  {
    "id": "mood-13",
    "category": "mood",
    "label": "心情",
    "title": "心情 · 13",
    "src": "images/mood/13.jpg",
    "thumb": "images/thumbs/mood/13.webp",
    "width": 1616,
    "height": 1080
  },
  {
    "id": "mood-14",
    "category": "mood",
    "label": "心情",
    "title": "心情 · 14",
    "src": "images/mood/14.jpg",
    "thumb": "images/thumbs/mood/14.webp",
    "width": 1125,
    "height": 2110
  },
  {
    "id": "mood-15",
    "category": "mood",
    "label": "心情",
    "title": "心情 · 15",
    "src": "images/mood/15.jpg",
    "thumb": "images/thumbs/mood/15.webp",
    "width": 1920,
    "height": 1280
  },
  {
    "id": "mood-16",
    "category": "mood",
    "label": "心情",
    "title": "心情 · 16",
    "src": "images/mood/16.jpg",
    "thumb": "images/thumbs/mood/16.webp",
    "width": 1918,
    "height": 1280
  },
  {
    "id": "mood-17",
    "category": "mood",
    "label": "心情",
    "title": "心情 · 17",
    "src": "images/mood/17.jpg",
    "thumb": "images/thumbs/mood/17.webp",
    "width": 639,
    "height": 635
  },
  {
    "id": "mood-18",
    "category": "mood",
    "label": "心情",
    "title": "心情 · 18",
    "src": "images/mood/18.jpg",
    "thumb": "images/thumbs/mood/18.webp",
    "width": 1280,
    "height": 960
  },
  {
    "id": "mood-19",
    "category": "mood",
    "label": "心情",
    "title": "心情 · 19",
    "src": "images/mood/19.jpg",
    "thumb": "images/thumbs/mood/19.webp",
    "width": 1279,
    "height": 1706
  },
  {
    "id": "landscape-1",
    "category": "landscape",
    "label": "风景",
    "title": "风景 · 01",
    "src": "images/landscape/1.jpg",
    "thumb": "images/thumbs/landscape/1.webp",
    "width": 1280,
    "height": 1706
  },
  {
    "id": "landscape-2",
    "category": "landscape",
    "label": "风景",
    "title": "风景 · 02",
    "src": "images/landscape/2.jpg",
    "thumb": "images/thumbs/landscape/2.webp",
    "width": 1276,
    "height": 1702
  },
  {
    "id": "landscape-3",
    "category": "landscape",
    "label": "风景",
    "title": "风景 · 03",
    "src": "images/landscape/3.jpg",
    "thumb": "images/thumbs/landscape/3.webp",
    "width": 1280,
    "height": 1707
  },
  {
    "id": "landscape-4",
    "category": "landscape",
    "label": "风景",
    "title": "风景 · 04",
    "src": "images/landscape/4.jpg",
    "thumb": "images/thumbs/landscape/4.webp",
    "width": 1280,
    "height": 1707
  },
  {
    "id": "landscape-5",
    "category": "landscape",
    "label": "风景",
    "title": "风景 · 05",
    "src": "images/landscape/5.jpg",
    "thumb": "images/thumbs/landscape/5.webp",
    "width": 2275,
    "height": 1279
  },
  {
    "id": "landscape-6",
    "category": "landscape",
    "label": "风景",
    "title": "风景 · 06",
    "src": "images/landscape/6.jpg",
    "thumb": "images/thumbs/landscape/6.webp",
    "width": 2276,
    "height": 1280
  },
  {
    "id": "landscape-7",
    "category": "landscape",
    "label": "风景",
    "title": "风景 · 07",
    "src": "images/landscape/7.jpg",
    "thumb": "images/thumbs/landscape/7.webp",
    "width": 2275,
    "height": 1279
  },
  {
    "id": "landscape-8",
    "category": "landscape",
    "label": "风景",
    "title": "风景 · 08",
    "src": "images/landscape/8.jpg",
    "thumb": "images/thumbs/landscape/8.webp",
    "width": 2275,
    "height": 1279
  },
  {
    "id": "landscape-9",
    "category": "landscape",
    "label": "风景",
    "title": "风景 · 09",
    "src": "images/landscape/9.jpg",
    "thumb": "images/thumbs/landscape/9.webp",
    "width": 2275,
    "height": 1279
  },
  {
    "id": "landscape-10",
    "category": "landscape",
    "label": "风景",
    "title": "风景 · 10",
    "src": "images/landscape/10.jpg",
    "thumb": "images/thumbs/landscape/10.webp",
    "width": 1276,
    "height": 958
  },
  {
    "id": "landscape-11",
    "category": "landscape",
    "label": "风景",
    "title": "风景 · 11",
    "src": "images/landscape/11.jpg",
    "thumb": "images/thumbs/landscape/11.webp",
    "width": 1702,
    "height": 1276
  },
  {
    "id": "landscape-12",
    "category": "landscape",
    "label": "风景",
    "title": "风景 · 12",
    "src": "images/landscape/12.jpg",
    "thumb": "images/thumbs/landscape/12.webp",
    "width": 1280,
    "height": 1600
  },
  {
    "id": "landscape-13",
    "category": "landscape",
    "label": "风景",
    "title": "风景 · 13",
    "src": "images/landscape/13.jpg",
    "thumb": "images/thumbs/landscape/13.webp",
    "width": 1282,
    "height": 1602
  },
  {
    "id": "landscape-14",
    "category": "landscape",
    "label": "风景",
    "title": "风景 · 14",
    "src": "images/landscape/14.jpg",
    "thumb": "images/thumbs/landscape/14.webp",
    "width": 2275,
    "height": 1279
  },
  {
    "id": "landscape-15",
    "category": "landscape",
    "label": "风景",
    "title": "风景 · 15",
    "src": "images/landscape/15.jpg",
    "thumb": "images/thumbs/landscape/15.webp",
    "width": 2275,
    "height": 1279
  },
  {
    "id": "landscape-16",
    "category": "landscape",
    "label": "风景",
    "title": "风景 · 16",
    "src": "images/landscape/16.jpg",
    "thumb": "images/thumbs/landscape/16.webp",
    "width": 2275,
    "height": 1279
  },
  {
    "id": "landscape-17",
    "category": "landscape",
    "label": "风景",
    "title": "风景 · 17",
    "src": "images/landscape/17.jpg",
    "thumb": "images/thumbs/landscape/17.webp",
    "width": 2275,
    "height": 1279
  },
  {
    "id": "landscape-18",
    "category": "landscape",
    "label": "风景",
    "title": "风景 · 18",
    "src": "images/landscape/18.jpg",
    "thumb": "images/thumbs/landscape/18.webp",
    "width": 1280,
    "height": 1919
  },
  {
    "id": "landscape-19",
    "category": "landscape",
    "label": "风景",
    "title": "风景 · 19",
    "src": "images/landscape/19.jpg",
    "thumb": "images/thumbs/landscape/19.webp",
    "width": 1702,
    "height": 1276
  },
  {
    "id": "landscape-20",
    "category": "landscape",
    "label": "风景",
    "title": "风景 · 20",
    "src": "images/landscape/20.jpg",
    "thumb": "images/thumbs/landscape/20.webp",
    "width": 1276,
    "height": 1276
  },
  {
    "id": "landscape-21",
    "category": "landscape",
    "label": "风景",
    "title": "风景 · 21",
    "src": "images/landscape/21.jpg",
    "thumb": "images/thumbs/landscape/21.webp",
    "width": 1918,
    "height": 1280
  },
  {
    "id": "landscape-22",
    "category": "landscape",
    "label": "风景",
    "title": "风景 · 22",
    "src": "images/landscape/22.jpg",
    "thumb": "images/thumbs/landscape/22.webp",
    "width": 1876,
    "height": 1280
  },
  {
    "id": "landscape-23",
    "category": "landscape",
    "label": "风景",
    "title": "风景 · 23",
    "src": "images/landscape/23.jpg",
    "thumb": "images/thumbs/landscape/23.webp",
    "width": 2275,
    "height": 1279
  },
  {
    "id": "landscape-24",
    "category": "landscape",
    "label": "风景",
    "title": "风景 · 24",
    "src": "images/landscape/24.jpg",
    "thumb": "images/thumbs/landscape/24.webp",
    "width": 2275,
    "height": 1279
  },
  {
    "id": "landscape-25",
    "category": "landscape",
    "label": "风景",
    "title": "风景 · 25",
    "src": "images/landscape/25.jpg",
    "thumb": "images/thumbs/landscape/25.webp",
    "width": 1280,
    "height": 960
  },
  {
    "id": "travel-1",
    "category": "travel",
    "label": "旅行",
    "title": "旅行 · 01",
    "src": "images/travel/1.jpg",
    "thumb": "images/thumbs/travel/1.webp",
    "width": 1933,
    "height": 1280
  },
  {
    "id": "travel-2",
    "category": "travel",
    "label": "旅行",
    "title": "旅行 · 02",
    "src": "images/travel/2.jpg",
    "thumb": "images/thumbs/travel/2.webp",
    "width": 1933,
    "height": 1280
  },
  {
    "id": "travel-3",
    "category": "travel",
    "label": "旅行",
    "title": "旅行 · 03",
    "src": "images/travel/3.jpg",
    "thumb": "images/thumbs/travel/3.webp",
    "width": 1933,
    "height": 1280
  },
  {
    "id": "travel-4",
    "category": "travel",
    "label": "旅行",
    "title": "旅行 · 04",
    "src": "images/travel/4.jpg",
    "thumb": "images/thumbs/travel/4.webp",
    "width": 966,
    "height": 640
  },
  {
    "id": "travel-5",
    "category": "travel",
    "label": "旅行",
    "title": "旅行 · 05",
    "src": "images/travel/5.jpg",
    "thumb": "images/thumbs/travel/5.webp",
    "width": 966,
    "height": 640
  },
  {
    "id": "travel-6",
    "category": "travel",
    "label": "旅行",
    "title": "旅行 · 06",
    "src": "images/travel/6.jpg",
    "thumb": "images/thumbs/travel/6.webp",
    "width": 1918,
    "height": 1280
  },
  {
    "id": "travel-7",
    "category": "travel",
    "label": "旅行",
    "title": "旅行 · 07",
    "src": "images/travel/7.jpg",
    "thumb": "images/thumbs/travel/7.webp",
    "width": 1933,
    "height": 1280
  },
  {
    "id": "travel-8",
    "category": "travel",
    "label": "旅行",
    "title": "旅行 · 08",
    "src": "images/travel/8.jpg",
    "thumb": "images/thumbs/travel/8.webp",
    "width": 1918,
    "height": 1280
  },
  {
    "id": "travel-9",
    "category": "travel",
    "label": "旅行",
    "title": "旅行 · 09",
    "src": "images/travel/9.jpg",
    "thumb": "images/thumbs/travel/9.webp",
    "width": 1918,
    "height": 1280
  },
  {
    "id": "travel-10",
    "category": "travel",
    "label": "旅行",
    "title": "旅行 · 10",
    "src": "images/travel/10.jpg",
    "thumb": "images/thumbs/travel/10.webp",
    "width": 1918,
    "height": 1280
  },
  {
    "id": "travel-11",
    "category": "travel",
    "label": "旅行",
    "title": "旅行 · 11",
    "src": "images/travel/11.jpg",
    "thumb": "images/thumbs/travel/11.webp",
    "width": 1918,
    "height": 1280
  },
  {
    "id": "travel-12",
    "category": "travel",
    "label": "旅行",
    "title": "旅行 · 12",
    "src": "images/travel/12.jpg",
    "thumb": "images/thumbs/travel/12.webp",
    "width": 1920,
    "height": 1280
  },
  {
    "id": "travel-13",
    "category": "travel",
    "label": "旅行",
    "title": "旅行 · 13",
    "src": "images/travel/13.jpg",
    "thumb": "images/thumbs/travel/13.webp",
    "width": 1920,
    "height": 1280
  },
  {
    "id": "travel-14",
    "category": "travel",
    "label": "旅行",
    "title": "旅行 · 14",
    "src": "images/travel/14.jpg",
    "thumb": "images/thumbs/travel/14.webp",
    "width": 1920,
    "height": 1280
  },
  {
    "id": "travel-15",
    "category": "travel",
    "label": "旅行",
    "title": "旅行 · 15",
    "src": "images/travel/15.jpg",
    "thumb": "images/thumbs/travel/15.webp",
    "width": 1920,
    "height": 1280
  },
  {
    "id": "travel-16",
    "category": "travel",
    "label": "旅行",
    "title": "旅行 · 16",
    "src": "images/travel/16.jpg",
    "thumb": "images/thumbs/travel/16.webp",
    "width": 1920,
    "height": 1280
  },
  {
    "id": "travel-17",
    "category": "travel",
    "label": "旅行",
    "title": "旅行 · 17",
    "src": "images/travel/17.jpg",
    "thumb": "images/thumbs/travel/17.webp",
    "width": 1920,
    "height": 1280
  },
  {
    "id": "travel-18",
    "category": "travel",
    "label": "旅行",
    "title": "旅行 · 18",
    "src": "images/travel/18.jpg",
    "thumb": "images/thumbs/travel/18.webp",
    "width": 1280,
    "height": 1920
  },
  {
    "id": "travel-19",
    "category": "travel",
    "label": "旅行",
    "title": "旅行 · 19",
    "src": "images/travel/19.jpg",
    "thumb": "images/thumbs/travel/19.webp",
    "width": 1450,
    "height": 960
  },
  {
    "id": "travel-20",
    "category": "travel",
    "label": "旅行",
    "title": "旅行 · 20",
    "src": "images/travel/20.jpg",
    "thumb": "images/thumbs/travel/20.webp",
    "width": 1920,
    "height": 1080
  },
  {
    "id": "travel-21",
    "category": "travel",
    "label": "旅行",
    "title": "旅行 · 21",
    "src": "images/travel/21.jpg",
    "thumb": "images/thumbs/travel/21.webp",
    "width": 1920,
    "height": 1080
  },
  {
    "id": "travel-22",
    "category": "travel",
    "label": "旅行",
    "title": "旅行 · 22",
    "src": "images/travel/22.jpg",
    "thumb": "images/thumbs/travel/22.webp",
    "width": 1920,
    "height": 1080
  },
  {
    "id": "travel-23",
    "category": "travel",
    "label": "旅行",
    "title": "旅行 · 23",
    "src": "images/travel/23.jpg",
    "thumb": "images/thumbs/travel/23.webp",
    "width": 1278,
    "height": 1794
  },
  {
    "id": "travel-24",
    "category": "travel",
    "label": "旅行",
    "title": "旅行 · 24",
    "src": "images/travel/24.jpg",
    "thumb": "images/thumbs/travel/24.webp",
    "width": 1707,
    "height": 1280
  },
  {
    "id": "travel-25",
    "category": "travel",
    "label": "旅行",
    "title": "旅行 · 25",
    "src": "images/travel/25.jpg",
    "thumb": "images/thumbs/travel/25.webp",
    "width": 1622,
    "height": 1284
  },
  {
    "id": "travel-26",
    "category": "travel",
    "label": "旅行",
    "title": "旅行 · 26",
    "src": "images/travel/26.jpg",
    "thumb": "images/thumbs/travel/26.webp",
    "width": 1702,
    "height": 1276
  },
  {
    "id": "travel-27",
    "category": "travel",
    "label": "旅行",
    "title": "旅行 · 27",
    "src": "images/travel/27.jpg",
    "thumb": "images/thumbs/travel/27.webp",
    "width": 1276,
    "height": 1276
  },
  {
    "id": "travel-28",
    "category": "travel",
    "label": "旅行",
    "title": "旅行 · 28",
    "src": "images/travel/28.jpg",
    "thumb": "images/thumbs/travel/28.webp",
    "width": 2275,
    "height": 1279
  },
  {
    "id": "travel-29",
    "category": "travel",
    "label": "旅行",
    "title": "旅行 · 29",
    "src": "images/travel/29.jpg",
    "thumb": "images/thumbs/travel/29.webp",
    "width": 2275,
    "height": 1279
  },
  {
    "id": "travel-30",
    "category": "travel",
    "label": "旅行",
    "title": "旅行 · 30",
    "src": "images/travel/30.jpg",
    "thumb": "images/thumbs/travel/30.webp",
    "width": 1707,
    "height": 1280
  },
  {
    "id": "night-1",
    "category": "night",
    "label": "夜景",
    "title": "夜景 · 01",
    "src": "images/night/1.jpg",
    "thumb": "images/thumbs/night/1.webp",
    "width": 1918,
    "height": 1280
  },
  {
    "id": "night-2",
    "category": "night",
    "label": "夜景",
    "title": "夜景 · 02",
    "src": "images/night/2.jpg",
    "thumb": "images/thumbs/night/2.webp",
    "width": 1933,
    "height": 1280
  },
  {
    "id": "night-3",
    "category": "night",
    "label": "夜景",
    "title": "夜景 · 03",
    "src": "images/night/3.jpg",
    "thumb": "images/thumbs/night/3.webp",
    "width": 1898,
    "height": 1280
  },
  {
    "id": "night-4",
    "category": "night",
    "label": "夜景",
    "title": "夜景 · 04",
    "src": "images/night/4.jpg",
    "thumb": "images/thumbs/night/4.webp",
    "width": 1440,
    "height": 961
  },
  {
    "id": "night-5",
    "category": "night",
    "label": "夜景",
    "title": "夜景 · 05",
    "src": "images/night/5.jpg",
    "thumb": "images/thumbs/night/5.webp",
    "width": 1440,
    "height": 961
  },
  {
    "id": "night-6",
    "category": "night",
    "label": "夜景",
    "title": "夜景 · 06",
    "src": "images/night/6.jpg",
    "thumb": "images/thumbs/night/6.webp",
    "width": 3088,
    "height": 1280
  },
  {
    "id": "night-7",
    "category": "night",
    "label": "夜景",
    "title": "夜景 · 07",
    "src": "images/night/7.jpg",
    "thumb": "images/thumbs/night/7.webp",
    "width": 2147,
    "height": 1280
  },
  {
    "id": "night-8",
    "category": "night",
    "label": "夜景",
    "title": "夜景 · 08",
    "src": "images/night/8.jpg",
    "thumb": "images/thumbs/night/8.webp",
    "width": 2276,
    "height": 1280
  },
  {
    "id": "night-9",
    "category": "night",
    "label": "夜景",
    "title": "夜景 · 09",
    "src": "images/night/9.jpg",
    "thumb": "images/thumbs/night/9.webp",
    "width": 2276,
    "height": 1280
  },
  {
    "id": "night-10",
    "category": "night",
    "label": "夜景",
    "title": "夜景 · 10",
    "src": "images/night/10.jpg",
    "thumb": "images/thumbs/night/10.webp",
    "width": 2276,
    "height": 1280
  },
  {
    "id": "night-11",
    "category": "night",
    "label": "夜景",
    "title": "夜景 · 11",
    "src": "images/night/11.jpg",
    "thumb": "images/thumbs/night/11.webp",
    "width": 1279,
    "height": 2275
  },
  {
    "id": "night-12",
    "category": "night",
    "label": "夜景",
    "title": "夜景 · 12",
    "src": "images/night/12.jpg",
    "thumb": "images/thumbs/night/12.webp",
    "width": 706,
    "height": 1140
  },
  {
    "id": "night-13",
    "category": "night",
    "label": "夜景",
    "title": "夜景 · 13",
    "src": "images/night/13.jpg",
    "thumb": "images/thumbs/night/13.webp",
    "width": 1920,
    "height": 1080
  }
];
