"""Run after adding photos: python scripts/build_gallery.py (requires Pillow)."""
import json
from pathlib import Path
from PIL import Image, ImageOps

ROOT = Path(__file__).resolve().parents[1]
CATEGORIES = [("mood", "心情"), ("landscape", "风景"), ("travel", "旅行"), ("night", "夜景")]
photos = []
for category, label in CATEGORIES:
    files = sorted((ROOT / "images" / category).glob("*.jpg"), key=lambda p: (0, int(p.stem)) if p.stem.isdigit() else (1, p.stem))
    for index, path in enumerate(files, 1):
        with Image.open(path) as source:
            picture = ImageOps.exif_transpose(source).convert("RGB")
            width, height = picture.size
            picture.thumbnail((960, 960))
            target = ROOT / "images" / "thumbs" / category / (path.stem + ".webp")
            target.parent.mkdir(parents=True, exist_ok=True)
            picture.save(target, "WEBP", quality=82)
        photos.append(dict(id=f"{category}-{path.stem}", category=category, label=label, title=f"{label} · {index:02d}", src=path.relative_to(ROOT).as_posix(), thumb=target.relative_to(ROOT).as_posix(), width=width, height=height))
(ROOT / "js" / "photos.js").write_text("// Generated by scripts/build_gallery.py; original photos are unchanged.\nwindow.GUXUE_PHOTOS = " + json.dumps(photos, ensure_ascii=False, indent=2) + ";\n", encoding="utf-8")
print(f"Built {len(photos)} photographs and previews.")
